version: '3.1'

services:
  app:
    depends_on:
      db:
        condition: service_healthy
    image: strori/testtask:0.0.1
    ports:
      - "80"
    networks:
      - db

  db:
    image: mysql:8.0.31
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ptesttask"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: testtask
      MYSQL_DATABASE: testtask
      MYSQL_PASSWORD: testtask
      MYSQL_USER: testtask
    volumes:
      - mysql:/var/lib/mysql
      - ./testdump.sql:/docker-entrypoint-initdb.d/testdump.sql
    networks:
      - db

volumes:
  mysql:
    driver: local

networks:
  db:
